/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -c LauncherInterface -p launcherinterface ddelauncher.xml
 *
 * qdbusxml2cpp is Copyright (C) 2015 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */
#include <QtDBus>
#include <QtDBus/QDBusAbstractInterface>
#include <QtDBus/QDBusArgument>
#include "dbusargument.h"
#include "launcherinterface.h"

/*
 * Implementation of interface class LauncherInterface
 */

LauncherInterface::LauncherInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
    CatalogInfo::registerMetaType();
    qRegisterMetaType<CatalogInfo>("CatalogInfo");
    qDBusRegisterMetaType<CatalogInfoList>();

    AppFrequency::registerMetaType();
    qRegisterMetaType<AppFrequency>("AppFrequency");
    qDBusRegisterMetaType<AppFrequencyList>();


    AppTimeInstalled::registerMetaType();
    qRegisterMetaType<AppTimeInstalled>("AppTimeInstalled");
    qDBusRegisterMetaType<AppTimeInstalledList>();


    AppInfo::registerMetaType();
    qRegisterMetaType<AppInfo>("AppInfo");
    qDBusRegisterMetaType<AppInfoList>();


}

LauncherInterface::~LauncherInterface()
{
}

